### PR TITLE
Automate git, gpg, gh, github desktop, text editor install and setup

### PR DESCRIPTION
**Pull request by namcios**
@ChristopherA creating this as a draft pull request first to gather feedback. If you could share your thoughts, it'd be great! The script has been tested with macOS Big Sur 11.5.2 on Intel Mac. Thanks

### CODE REVIEW

**Comment by namcios** [comment]
@ChristopherA most of feedback applied, more checks implemented, alternative method for uploading public keys to Github.com added too. Will do further testing tomorrow, and final tweaks if needed.

**Comment by namcios** [comment]
@ChristopherA tested on macOS Big Sur 11.5.2, everything should be working now. PR ready for review and merge.

**Comment by namcios** [comment]
@ChristopherA I'm happy with this now as an early draft, won't be adding more commits. Good for merging from my end.

**Review by ChristopherA — APPROVED** [review]
Approve for merge. Still needs some real user testing with a naive user.

**Pull request merged**
